[package]
name = "deno_doc"
version = "0.1.0"
authors = ["Bartek Iwańczuk <biwanczuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
lazy_static = "1.4.0"
deno_core = "0.53.0"
serde = { version = "1.0.115", features = ["derive"] }
serde_derive = "1.0.115"
serde_json = { version = "1.0.57", features = [ "preserve_order" ] }
swc_common = { version = "=0.9.1" }
swc_ecmascript = { version = "=0.3.1", features = ["parser"] }
termcolor = "1.1.0"
regex = "1.3.9"

[dev-dependencies]
tokio = { version = "0.2.22", features = ["full"] }